name: Baby Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch_build:
        description: "Branch to build"
        required: true
        type: choice
        options:
          - dev
          - master
      micro_serv:
        description: "Micro Service??"
        required: true
        type: choice
        options:
          - preper
          - downloader

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ fromJSON('{
          "dev": "dev",
          "master": "prod",
          "staging": "staging",
          "qa": "qa"
        }')[inputs.branch_build] }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        working-directory: "SSScrapey-rework/docker"
        run: |
          echo "hello mofo" && pwd

      - name: Build and push multi-arch Docker image
        working-directory: "SSScrapey-rework/docker"
        run: |
          MICRO=${{ github.event.inputs.micro_serv }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg ENV_TYPE=${ENV} \
            --no-cache \
            -f Dockerfile_ECS_${MICRO} \
            -t cbrodski/${MICRO}:official_v2_${ENV} \
            --push \
            .
    # --push Required for multi-arch images, because Buildx cant store them locally
    # test 123