name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "dev"
      build_dir:
        description: "Directory containing the Dockerfile"
        required: true
        default: "./SSScrapey-rework/docker/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkotu code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set working directory
        working-directory: ${{ github.event.inputs.build_dir }}
        run: echo "Building in $PWD"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        working-directory: ${{ github.event.inputs.build_dir }}
        run: |
          echo "hello mofo"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push multi-arch image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile_ECS_preper
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: cbrodski/preper:official_v2_dev
