name: Baby Build and Push Docker Image

on:
  push:
    branches:
      - mainX
      - masterX
  workflow_dispatch:
    inputs:
      branch_build:
        description: "Branch to build"
        required: true
        type: choice
        options:
          - dev
          - prod
      micro_serv:
        description: "Micro Service??"
        required: true
        default: "preper"
        type: choice
        options:
          - preper
          - downloader
          - transcriber

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # - name: Set working directory
      #   working-directory: ${{ github.event.inputs.build_dir }}
      #   run: echo "Building in $PWD"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        working-directory: "SSScrapey-rework/docker"
        run: |
          echo "hello mofo" && pwd

      - name: Build and push multi-arch Docker image
        working-directory: "SSScrapey-rework/docker"
        run: |
          ENV=${{ github.event.inputs.branch_build }}
          MICRO=${{ github.event.inputs.micro_serv }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg ENV_TYPE=${ENV} \
            --no-cache \
            -f Dockerfile_ECS_${MICRO} \
            -t cbrodski/${MICRO}:official_v2_${ENV} \
            --push \
            .
    # --push Required for multi-arch images, because Buildx cant store them locally
